# Generated by Django 3.2.6 on 2021-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210920_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='customers', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='employees', verbose_name='Image'),
        ),
    ]
