# Generated by Django 3.2.6 on 2021-09-29 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210927_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
