# Generated by Django 3.2.6 on 2021-10-16 01:34

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=app.models.Customer.imagename),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=app.models.Employee.imagename),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=app.models.Invoice.pdfname, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
