# Generated by Django 3.2.6 on 2021-10-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211016_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_date',
            new_name='date_paid',
        ),
    ]
