# Generated by Django 3.2.6 on 2021-10-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211012_1859'),
        ('app', '0015_rename_payment_date_invoice_date_paid'),
    ]

    operations = [
    ]
